export enum CorrectionCode {
    DEVOLUCION_O_NO_ACEPTACION = 1,
    ANULACION_FACTURA = 2,
    REBAJA_DESCUENTO = 3,
    AJUSTE_PRECIO = 4,
    DESCUENTO_PRONTO_PAGO = 5,
    DESCUENTO_POR_VOLUMEN = 6,
  }
